
services:
 database:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: Booger1234
     MYSQL_DATABASE: myDB
     MYSQL_USER: Samuel
     MYSQL_PASSWORD: Dork5678
   ports:
     - 6603:3306
   volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5

